# Generated by Django 4.2.18 on 2025-03-04 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reset_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_when", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                (
                    "coordinator_name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                (
                    "coordinator_type",
                    models.CharField(
                        choices=[
                            ("club", "Club Coordinator"),
                            ("department", "Department Coordinator"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.CharField(max_length=25)),
                ("password", models.CharField(max_length=25)),
                (
                    "phone_no",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                (
                    "club_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.club",
                    ),
                ),
                (
                    "department_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.department",
                    ),
                ),
            ],
        ),
    ]
