# Generated by Django 4.2.18 on 2025-03-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "club_name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("club_description", models.TextField()),
                (
                    "club_poster",
                    models.ImageField(blank=True, upload_to="club_posters/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=25)),
                ("department_description", models.TextField()),
                (
                    "department_poster",
                    models.ImageField(blank=True, upload_to="department_posters/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=25)),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
                ("event_time", models.CharField(max_length=100)),
                (
                    "event_poster",
                    models.ImageField(blank=True, upload_to="event_posters/"),
                ),
                ("event_venue", models.CharField(max_length=40)),
                ("registration_link", models.URLField(blank=True, null=True)),
                (
                    "club_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.club",
                    ),
                ),
                (
                    "department_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="department_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="event.department",
            ),
        ),
    ]
