# Generated by Django 4.2.18 on 2025-03-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="department_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="event.department",
            ),
        ),
    ]
