# Generated by Django 4.2.18 on 2025-02-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('event_poster', models.ImageField(blank=True, upload_to='event_posters/')),
                ('event_venue', models.CharField(max_length=40)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.department')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('club_description', models.TextField()),
                ('club_poster', models.ImageField(blank=True, upload_to='club_posters/')),
                ('department_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.department')),
            ],
        ),
    ]
