# Generated by Django 4.2.18 on 2025-03-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fest",
            fields=[
                (
                    "fest_name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
                (
                    "fest_poster",
                    models.ImageField(blank=True, upload_to="fest_posters/"),
                ),
                (
                    "department_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="dEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=25)),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
                ("event_time", models.CharField(max_length=100)),
                (
                    "event_poster",
                    models.ImageField(blank=True, upload_to="event_posters/"),
                ),
                ("event_venue", models.CharField(max_length=40)),
                ("registration_link", models.URLField(blank=True, null=True)),
                (
                    "department_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.department",
                    ),
                ),
                (
                    "fest_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.fest",
                    ),
                ),
            ],
        ),
    ]
