# Generated by Django 4.2.18 on 2025-03-28 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devent",
            name="fest_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.fest",
            ),
        ),
    ]
